# Planteamiento del Problema

Los efectos negativos de la pandemia en las principales variables macroeconómicas no son ninguna sorpresa, pues para responder a la emergencia de salud planteada por el Covid-19 se tomaron medidas que significaron un trade-off entre la salud pública y la salud de la economía de los territorios. Ante esto, la ciudad de Barranquilla no fue la excepción, ya que se suspendieron alrededor del 90% de las actividades económicas, lo cual significo un retroceso en los diferentes indicadores sociales y de desarrollo, teniendo en cuenta las condiciones socioeconómicas de la población barranquillera respecto a las clases sociales y factores de riesgo de los pobres.

## Pregunta de investigacíon

¿La reducción de la pobreza en Barranquilla ha sido de carácter pro pobre o anti pobre?  La respuesta a esta interrogante permitirá comprender con mayor detalle el fenómeno de pobreza existente en Barranquilla.

### Objetivos 

Objetivo General

1.1 Realizar una caracterización de la pobreza con enfoque de inclusión productiva y social en la población Barranquillera para determinar si el crecimiento económico ha sido pro-pobre o anti-pobre.

Objetivos Específicos

1.1.1 Caracterizar y detallar la evolución de la pobreza monetaria y del PIB en Barranquilla en el periodo 2010 – 2021.

1.1.2 Examinar la evolución de la pobreza monetaria y del PIB en las principales ciudades contrastadas al total nacional en el periodo 2010 – 2021.

1.1.3 Caracterizar socioeconómicamente la población barranquillera en el periodo 2010 – 2021.

1.1.4 Contrastar el índice de pobreza multidimensional de Barranquilla con las principales ciudades y el total nacional en el año 2018.

1.1.5 Descomponer el índice de pobreza multidimensional en sus componentes para Barranquilla en el año 2018.

1.1.6 Caracterizar según clases sociales el componente de micronegocios en Barranquilla.

1.1.7 Descomponer el cambio de la pobreza en sus efectos de crecimiento, redistribución e inflación de la línea de pobreza utilizando la metodología de Kolenikov – Shorrocks.

1.1.8 Identificar por qué vías (Crecimiento, Redistribución, Línea de pobreza) se ha producido la reducción de la pobreza en Barranquilla.

1.1.9 Identificar retos que obstaculicen la reducción de la pobreza en Barranquilla.
