# Pobreza y crecimiento en Barranquilla A.M.

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
library(dplyr)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(gganimate)
#Primero
factor<-450
grafico_base = pobreza_y_crecimiento %>%
  ggplot(aes(x=año))+
  geom_line(aes(y=Pobreza, color="Pobreza"), size=1.2)+
  geom_point(aes(y=Pobreza), size=6,color="green")+
  geom_label(aes(x=año,y=Pobreza,label=sprintf("%0.2f",round(Pobreza,digits=2))),
             nudge_x=0.5,
             nudge_y=2,
             size=6,
             hjust=1)+
  geom_line(aes(y=`Pobreza extrema`,color="Pobreza extrema"), size=1.2)+
  geom_point(aes(y=`Pobreza extrema`), size=6,color="blue")+
  geom_label(aes(x=año,y=`Pobreza extrema`,label=sprintf("%0.2f",round(`Pobreza extrema`,digits=2))),
             nudge_x=0.25,
             nudge_y=2,
             size=6,
             hjust=1)+
  geom_line(aes(y=PIB/factor,color="PIB"),size=1.2,linetype=5)+
  geom_point(aes(y=PIB/factor),size=6,color="red")+
  geom_label(aes(x=año,y=PIB/factor,label=sprintf("%0.2f",round(PIB,digits=2))),
             nudge_x=0.25,
             nudge_y=-2,
             size=6,
             hjust=1)+
  scale_y_continuous(sec.axis=sec_axis(trans=~.*factor,name="PIB per cápita (miles de pesos)"))+
  scale_color_discrete("")+
  scale_x_continuous(breaks = c(2011,2013,2016,2019,2021))+
  labs(title="Evolución de la pobreza monetaria y del PIB",
       subtitle="Barranquilla A.M. 2011 - 2021",
       y="Pobreza (%)",
       x="",
       tag="Figura 1",
       caption="Fuente: Pobreza Monetaria - Cuentas Nacionales, DANE (2021)")+
  transition_reveal(año)+
  shadow_mark(past=FALSE)+
  #view_follow(fixed_x = TRUE) +
  enter_appear(early = FALSE) +
  enter_grow() +
  enter_fade(alpha = 0) +
  theme_bw() +
  theme(panel.grid.major.x = element_blank(),
        plot.title = element_text(size = 25, 
                                  face = "bold", 
                                  hjust = 0),
        plot.subtitle = element_text(size=20, 
                                     face = "bold", 
                                     hjust = 0, 
                                     color = "orange"),
        axis.title.x=element_text(color="black",size=20),
        axis.title.y=element_text(color="black",size=20),
        plot.caption= element_text(size=20),
        legend.title=element_text(color="black",size=20),
        legend.text = element_text(color="black",size=20),
        axis.text=element_text(size=20),
        plot.tag= element_text(size=20),
        plot.margin= unit(c(t = 1, r = 2, b = 1, l = 2), "cm"),
        legend.position = "bottom",
        plot.background = element_rect(fill="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"))
animate(grafico_base, nframes= 400, width = 1000, height= 600, fps = 20,end_pause=60)
  

```

# Comparación con otras ciudades
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Segundo_grafico %>%
  mutate(Segundo_grafico,isBarranquilla = Ciudad=="Barranquilla A.M.") %>%
  ggplot(aes(x=Año, y=Pobreza, color=Ciudad))+
  geom_line(aes(linetype=isBarranquilla),linewidth=1.25, alpha=0.8)+
  theme_bw()+
  scale_x_continuous(breaks = c(2011,2013,2016,2019,2021))+
  labs(title="Evolución de la pobreza",
       subtitle="Pobreza monetaria de las principales ciudades 2011 - 2021",
       x="Años",
       y="Pobreza (%)",
       tag="Figura 2",
       color="Ciudad",
       caption="Fuente: Pobreza monetaria - DANE (2021)")+
  theme(axis.title=element_text(),
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="orange",size=10,face="bold"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"),
        plot.tag.position="topleft",
        plot.background = element_rect(fill="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        legend.text=element_text(size=10),plot.caption.position="plot",plot.caption=element_text(color="black",size=12,hjust=0),legend.position="bottom")+
  scale_color_brewer(palette="Set2")+
  scale_linetype_manual(values=c("dashed","solid"),guide="none")



```

# Evolución del PIB - Barranquilla
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
animado3=Tercer_grafico %>%
  mutate(Tercer_grafico,isBarranquilla = Ciudad=="Barranquilla A.M.") %>%
  ggplot(aes(x=Año, y=Indice, color=Ciudad))+
  geom_line(aes(linetype=isBarranquilla),linewidth=1.25, alpha=0.8)+
  geom_point(size=3)+
  theme_bw()+
  scale_x_continuous(breaks = c(2010,2013,2016,2019,2021))+
  labs(title="Índice de la evolución del PIB (Año base = 2010)",
       subtitle="Como ha crecido el PIB per cápita en las principales ciudades?",
       x="",
       y="Var. porcentual (%)",
       tag="Figura 3",
       color="Ciudad",
       caption="Fuente: Cálculos del autor con base en DANE (2021)")+
  theme(plot.tag.position="topleft",
        legend.title=element_text(color="black",size=15,face="bold"),
        plot.subtitle=element_text(color="orange",size=15,face="bold"),
        axis.title.x=element_text(color="black",size=20),
        axis.title.y=element_text(color="black",size=20),
        plot.title = element_text(color="black",size=20,face="bold"),
        plot.tag= element_text(size=20),
        plot.background = element_rect(fill="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title=element_text(),
        legend.text=element_text(size=20),plot.caption.position="plot",plot.caption=element_text(color="black",size=20,hjust=0),legend.position="bottom")+
  scale_color_brewer(palette="Set2")+
  scale_linetype_manual(values=c("dashed","solid"),guide="none")+
  transition_reveal(Año)+
  shadow_mark(past=FALSE)+
  #view_follow(fixed_x = TRUE) +
  enter_appear(early = FALSE) +
  enter_grow() +
  enter_fade(alpha = 0)
animate(animado3, nframes= 400, width = 1000, height= 600, fps = 20)

```


# evolucion principales ciudades
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
factor2=9000
Tercer_grafico %>%
  mutate(Tercer_grafico,isBarranquilla = Ciudad=="Barranquilla A.M.") %>%
  ggplot(aes(x=Año, y=PIB/factor2, color=Ciudad))+
  geom_line(aes(linetype=isBarranquilla),linewidth=1.25, alpha=0.8)+
  geom_point(size=3)+
  theme_bw()+
  scale_x_continuous(breaks = c(2010,2013,2016,2019,2021))+
  labs(title="Índice de la evolución del PIB (Año base = 2010)",
       subtitle="Como ha crecido el PIB per cápita en las principales ciudades?",
       x="",
       y="Var. porcentual (%)",
       tag="Figura 4",
       color="Ciudad",
       caption="Fuente: Cálculos del autor con base en DANE (2021)")+
  theme(plot.tag.position="topleft",
        legend.title=element_text(color="black",size=15,face="bold"),
        plot.subtitle=element_text(color="orange",size=15,face="bold"),
        axis.title.x=element_text(color="black",size=20),
        axis.title.y=element_text(color="black",size=20),
        plot.title = element_text(color="black",size=20,face="bold"),
        plot.tag= element_text(size=20),
        plot.background = element_rect(fill="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title=element_text(),
        legend.text=element_text(size=15),plot.caption.position="plot",plot.caption=element_text(color="black",size=20,hjust=0),legend.position="bottom")+
  scale_color_brewer(palette="Set2")+
  scale_linetype_manual(values=c("dashed","solid"),guide="none")
```

