# Caracterizacíon Socioeconomica

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
library(dplyr)
library(ggplot2)
Cuarto_grafico %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase social`))+
  geom_bar(stat="identity")+
  theme_minimal()+
  labs(title="Clases sociales en Barranquilla",
       subtitle="Como ha sido la distribucion socioeconomica de la poblacion barranquillera?",
       x="Años",
       y="Proporcion",
       tag="Figura 4",
       caption="Fuente:DANE (2022)")+
  theme(axis.title=element_text(),
        legend.text=element_text(size=10),plot.caption.position="plot",plot.caption=element_text(hjust=0),legend.position="bottom")+
  scale_color_brewer(palette="Set2")
  
```

# Indice de pobreza multidimensional principales ciudades

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Quinto_grafico %>%
  ggplot(aes(x=Ciudad,y=IPM,fill=Ciudad))+
  geom_bar(stat="identity")+
  theme_minimal()+
  labs(title="IPM Principales Ciudades - 2018",
       subtitle="Mas alla del ingreso, cual es la situación de la pobreza en Barranquilla",
       x="Ciudad",
       y="IPM",
       tag="Figura 5",
       caption="Fuente:DANE (2022)")+
  theme(axis.title=element_text(),
        legend.text=element_text(size=10),plot.caption.position="plot",plot.caption=element_text(hjust=0),legend.position="bottom")+
  scale_color_brewer(palette="Set2")+
  scale_x_discrete(breaks=NULL)
```

# Componentes del IPM para Barranquilla

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Sexto_grafico %>%
  ggplot(aes(x=Proporcion,y=Sexto_grafico$`Componentes IPM`))+
  geom_bar(stat="identity",fill="skyblue")+
  theme_minimal()+
  labs(title="Componentes IMP",
       subtitle="Analisis desagregado del IPM para Barranquilla en 2018",
       x=" ",
       y=" ",
       tag="Figura 6",
       caption="Fuente:DANE (2022)")+
  theme(axis.title=element_text(),
        plot.caption.position="plot",plot.caption=element_text(hjust=0))
  
```

# Caracterizacion socioeconomica de los micronegocios de Barranquilla

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Septimo_grafico %>%
  ggplot(aes(x=Año,y=Proporcion,fill=Clase))+
  geom_bar(stat="identity")+
  scale_x_continuous(breaks=c(2020,2021))+
  theme_minimal()+
  labs(title="Caracterización micronegocios",
       subtitle="Analisis por clases sociales de los micronegocios en Barranquilla 2020-2021",
       x=" ",
       y=" ",
       tag="Figura 7",
       caption="Fuente: Calculos del autor con base en DANE (2022)")+
  theme(axis.title=element_text(),
        plot.caption.position="plot",plot.caption=element_text(hjust=0))
```

