# Caracterizacíon Socioeconomica

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
library(forcats)

g1=Cuarto_grafico %>%
  mutate(`Clase social`=fct_relevel(`Clase social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase social`))+
  geom_bar(stat="identity",width=0.8)+
  geom_text(aes(label=Proporcion),
            position=position_stack(vjust=0.5),
            color="black",
            size=3.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Barranquilla A.M.",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          legend.key=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

g2=Cuarto_grafico_2 %>%
  mutate(`Clase Social`=fct_relevel(`Clase Social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase Social`))+
  geom_bar(stat="identity",width=0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Bogotá",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          legend.key=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

g3=Cuarto_grafico_3 %>%
  mutate(`Clase Social`=fct_relevel(`Clase Social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase Social`))+
  geom_bar(stat="identity",width=0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Bucaramanga A.M.",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          rect=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

g4=Cuarto_grafico_4 %>%
  mutate(`Clase Social`=fct_relevel(`Clase Social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase Social`))+
  geom_bar(stat="identity",width=0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Calí A.M.",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          rect=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

g5=Cuarto_grafico_5 %>%
  mutate(`Clase Social`=fct_relevel(`Clase Social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase Social`))+
  geom_bar(stat="identity",width=0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Cartagena",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          rect=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

g6=Cuarto_grafico_6 %>%
  mutate(`Clase Social`=fct_relevel(`Clase Social`,"Clase Alta","Clase Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=`Clase Social`))+
  geom_bar(stat="identity",width=0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(
    title="Medellín A.M.",
    x="",
    y=""
  )+theme(plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
          legend.key=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"))

library(ggpubr)
figura<-ggarrange(g1,g2,g3,g4,g5,g6,common.legend = TRUE, legend="bottom")
annotate_figure(figura,fig.lab = "",fig.lab.face = "bold",
                top=text_grob("Distribución de clases sociales",face="bold"),
                bottom =text_grob("Fuente: Pobreza monetaria, Caracterización clases sociales, DANE (2021)",hjust=1,x=1))
  
```

# Indice de pobreza multidimensional

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Quinto_grafico %>%
  ggplot(aes(x=reorder(Ciudad,-IPM),y=IPM,fill=IPM))+
  geom_bar(stat="identity", width=0.5)+
  geom_text(label=(Quinto_grafico$IPM),
            nudge_x=0.015,nudge_y=0.5,
            check_overlap=T)+
  theme_bw()+
  labs(title="IPM Principales Ciudades - 2018",
       subtitle="Mas alla del ingreso, cual es la situación de la pobreza?",
       x="",
       y="IPM",
       tag="",
       caption="Fuente: Pobreza multidimensional, Censo Económico (2018)")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="none",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="black",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))
```

# Componentes del IPM para Barranquilla

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Sexto_grafico %>%
  mutate(`Componentes IPM`=fct_relevel(`Componentes IPM`,"Vivienda","Cond. De la niñez", "Salud","Cond. Educativas","Trabajo")) %>%
  ggplot(aes(`Componentes IPM`,y=Proporcion))+
  geom_bar(stat="identity", width=0.5, fill="royalblue4")+
  coord_flip()+
  geom_text(label=(Sexto_grafico$Proporcion),
            nudge_x=0.025,nudge_y=1,
            check_overlap=T)+
  theme_bw()+
  labs(
    title="Descomposición del IPM por dimensión",
    subtitle="Barranquilla A.M. - 2018",
    tag="",
    y="",
    x="Dimensión",
    caption="Fuente: Pobreza multidimensional, Censo Económico (2018)"
  )+theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="none",
          plot.tag.position="topright",
          legend.title=element_text(color="black",size=10,face="bold"),
          plot.subtitle=element_text(color="black",size=10,face="bold"),
          axis.title.x=element_text(color="black",size=12,face="bold"),
          plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
          legend.key=element_rect(fill="#F0F1EB"),
          axis.title.y=element_text(color="black",size=12,face="bold"))
  
```

# Informalidad barranquilla

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
p1=pobres %>%
  mutate(tipo=fct_relevel(tipo,"formal","informal")) %>%
  ggplot(aes(x=Año,y=Proporcion, fill=tipo))+
  geom_bar(stat="identity", width=0.5)+
  scale_x_continuous(breaks = c(2016,2017,2018,2019,2020,2021))+
  labs(
    title="Informalidad de la población pobre",
    subtitle="Barranquilla A.M. 2016 - 2021",
    y="Proporción (%)",
    fill=""
  )+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        axis.title.y=element_text(color="black",size=12,face="bold"))

p2=Vulnerables %>%
  mutate(tipo=fct_relevel(tipo,"formal","informal")) %>%
  ggplot(aes(x=Año,y=Proporcion, fill=tipo))+
  geom_bar(stat="identity", width=0.5)+
  scale_x_continuous(breaks = c(2016,2017,2018,2019,2020,2021))+
  labs(
    title="Informalidad de la población vulnerable",
    subtitle="Barranquilla A.M. 2016 - 2021",
    y="Proporción (%)",
    fill=""
  )+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))

p3=Clase_media %>%
  mutate(tipo=fct_relevel(tipo,"formal","informal")) %>%
  ggplot(aes(x=Año,y=Proporcion, fill=tipo))+
  geom_bar(stat="identity", width=0.5)+
  scale_x_continuous(breaks = c(2016,2017,2018,2019,2020,2021))+
  labs(
    title="Informalidad de la poblacion clase media",
    subtitle="Barranquilla A.M. 2016 - 2021",
    y="Proporción (%)",
    fill=""
  )+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))

p4=Clase_alta %>%
  mutate(tipo=fct_relevel(tipo,"formal","informal")) %>%
  ggplot(aes(x=Año,y=Proporcion, fill=tipo))+
  geom_bar(stat="identity", width=0.5)+
  scale_x_continuous(breaks = c(2016,2017,2018,2019,2020,2021))+
  labs(
    title="Informalidad de la poblacion clase alta",
    subtitle="Barranquilla A.M. 2016 - 2021",
    y="Proporción (%)",
    fill=""
  )+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB", colour="#F0F1EB"),
        legend.key=element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))

figura2<-ggarrange(p1,p2,p3,p4,common.legend = TRUE, legend="top")
annotate_figure(figura2,fig.lab = "",fig.lab.face = "bold",
                top=text_grob("Informalidad por Clases Sociales",face="bold"),
                bottom =text_grob("Fuente: Elaboración propia con base en GEIH (2016-2021)",hjust=1,x=1))

```



# Distribucion del empleo

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Noveno %>%
  mutate(tipo=fct_relevel(tipo,"formal","informal")) %>%
  ggplot(aes(x=estructura,y=Proporcion, fill=tipo))+
  geom_bar(stat="identity", width = 0.5)+
  coord_flip()+
  theme_bw()+
  labs(
    title="Distribución del empleo por tamaño de empresa y cuenta propia",
    subtitle="Barranquilla A.M. - 2021",
    tag="",
    y="Proporción (%)",
    x="",
    fill="",
    caption="Fuente: Cálculos del autor con base en GEIH (2021)"
  )+theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
          plot.tag.position="topright",
          legend.title=element_text(color="black",size=10,face="bold"),
          plot.subtitle=element_text(color="black",size=10,face="bold"),
          plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
          rect=element_rect(fill="#F0F1EB"),
          legend.background = element_rect(fill="#F0F1EB"),
          axis.title.x=element_text(color="black",size=12,face="bold"),
          axis.title.y=element_text(color="black",size=12,face="bold"))+
  scale_fill_brewer(palette="Paired")
```

# Micronegocios

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
Septimo_grafico %>%
  mutate(Clase=fct_relevel(Clase,"Alta","Media", "Vulnerable","Pobre")) %>%
  ggplot(aes(x=Año,y=Proporcion,fill=Clase))+
  geom_bar(stat="identity", width = 0.5)+
  scale_x_continuous(breaks=c(2019,2021))+
  scale_fill_brewer(palette = "Paired")+
  theme_bw()+
  labs(title="Propietarios de los micronegocios por clases sociales",
       subtitle="Barranquilla A.M. (2020 - 2021)",
       x=" ",
       y="Proporción (%)",
       tag="",
       fill="",
       caption="Fuente: Cálculos del autor con base en DANE EMICRON (2019-2021)")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="right",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="black",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
        rect=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))


```

# Micronegocios 2
```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
mpg1<-micronegocios_gra2 %>%
  ggplot(aes(x=proporcion,y=reto))+
  geom_bar(stat="identity", width = 0.5, fill="Royalblue4")+
  scale_y_discrete(limits=c("Capital semilla", "Prestamos bancarios", "Ahorros personales"))+
  theme_bw()+
  labs(title="Metodo de financiación 
       del micronegocio",
       subtitle="Barranquilla A.M. 2021",
       x="",
       y="Proporción (%)",
       caption="")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="right",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
        rect=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        axis.title.y=element_text(color="black",size=12,face="bold"))


#segundo reto
mpg2<-micronegocios_gra3 %>%
  ggplot(aes(x=reto,y=Proporcion1, fill=Tipo))+
  geom_bar(stat="identity", width = 0.5)+
  theme_bw()+
  scale_fill_brewer(palette="Paired")+
  labs(title="Micronegocios que no poseen TICS",
       subtitle="Barranquilla A.M. 2021",
       x="",
       y="Proporción (%)",tag="",
       fill="",
       caption="")+
  theme(plot.caption.position="plot",plot.caption=element_text(hjust=1),legend.position="top",
        plot.tag.position="topright",
        legend.title=element_text(color="black",size=10,face="bold"),
        plot.subtitle=element_text(color="grey",size=10,face="bold"),
        axis.title.x=element_text(color="black",size=12,face="bold"),
        plot.background = element_rect(fill="#F0F1EB",colour="#F0F1EB"),
        rect=element_rect(fill="#F0F1EB"),
        legend.background = element_rect(fill="#F0F1EB"),
        axis.title.y=element_text(color="black",size=12,face="bold"))

#uniendo graficos

figura2<-ggarrange(mpg1,mpg2)
annotate_figure(figura2,fig.lab = "",fig.lab.face = "bold",
                top=text_grob("Retos existentes en los micronegocios",face="bold"),
                bottom =text_grob("Fuente: EMICRON (2021)",hjust=1,x=1))
```



