# Metodología

Se parte de de los indíces de Foster, Greer & Thorbecke (1984):

$$FGT(\alpha)=\frac{1}{N}\sum_{i=1}^{q}(1-\frac{y_{i}}{z_{i}})^{\alpha}$$

Cuando α=0  el indice refleja la proporción de pobreza, cuando α=1 refleja la brecha de pobreza y cuando α=2 la severidad de la pobreza.

Luego, siguiendo la propuesta de Shorrocks-Kolenikov se reescribe la ecuación de la siguiente manera: $$P_{t}=FGT_{t}=P(y_{t},L_{t},z)$$. Y por ultimo, se procede a realizar la descomposicion definiendo los tres efectos:

$$Crecimiento=P(y_{1},L_{0},z_{0})-P(y_{0},L_{0},z_{0})$$ $$Redistribucion=P(y_{0},L_{1},z_{0})-P(y_{0},L_{0},z_{0})$$ $$Inflacion=P(y_{0},L_{0},z_{1})-P(y_{0},L_{0},z_{0})$$
Luego, se usa la propuesta del valor de Shapley para la obtencion de la contribucion marginal de cada efecto.

## Ejemplo

Se quiere descomponer el IDH en sus componentes de salud, educación e ingreso para identificar la contribución de cada factor en el cambio al pasar un año. En el 2020 el IDH registro un valor de 0,7 y en el 2021 de 0,75. Se cuenta además con los datos de cada componente para su respectivo año resumidos en la siguiente tabla.

|       |  salud |  educación |   PIB |
|-------|:------:|:----------:|:-----:|
|  2020 |   0,85 |     0,65   |  0,68 |
|  2021 |   0,89 |     0,68   |  0,69 |

Se hallan los efectos de la siguiente manera:

$$v(Salud)=[0,89+0,65+0,68]-[0,85+0,65+0,68]=0,04$$
$$v(educacion)=[0,85+0,68+0,68]-[0,85+0,65+0,68]=0,03$$
$$v(PIB)=[0,85+0,65+0,69]-[0,85+0,65+0,68]=0,01$$
Y finalmente, se multiplica el valor obtenido por la ponderacion proporcional de cada factor:

$$v(salud)=1/3*0,04=0,01, v(educacion)=1/3*0,03=0,01, v(PIB)=1/3*0,01=0,03$$


