# Resultados

La descomposición para la incidencia de la pobreza:

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
#Incidencia
library(ggplot2)
r1<-ggplot(resultados_2010_2013,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2010-2013")+theme(axis.title=element_text(),
          plot.caption.position="plot",plot.caption=element_text(hjust=0))

r2<-ggplot(resultados_2013_2016,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2013-2016")+theme(axis.title=element_text(),
          plot.caption.position="plot",plot.caption=element_text(hjust=0))

r3<-ggplot(resultados_2016_2019,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2016-2019")+theme(axis.title=element_text(),
          plot.caption.position="plot",plot.caption=element_text(hjust=0))

r4<-ggplot(resultados_2019_2021,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2019-2021")+theme(axis.title=element_text(),
          plot.caption.position="plot",plot.caption=element_text(hjust=0))
library(ggpubr)
figura2<-ggarrange(r1,r2,r3,r4,common.legend = TRUE,"legend=bottom")
annotate_figure(figura2,fig.lab="Figura 10",fig.lab.face = "bold",
                top=text_grob("Descomposición de la incidencia",face="bold"),
                bottom=text_grob("Fuente: Calculos del autor en base a Kolenikov-Shorrocks (2005)",hjust=1,x=1))

```

# Brecha de la pobreza

La descomposición para la brecha:

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
#Brecha
r5<-ggplot(resultados2_2010_2013,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2010-2013")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r6<-ggplot(resultados2_2013_2016,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2013-2016")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r7<-ggplot(resultados2_2016_2019,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2016-2019")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r8<-ggplot(resultados2_2019_2021,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2019-2021")+theme(axis.title=element_text(),                                 plot.caption.position="plot",plot.caption=element_text(hjust=0))

figura3<-ggarrange(r5,r6,r7,r8,common.legend = TRUE,"legend=bottom")
annotate_figure(figura3,fig.lab="Figura 11",fig.lab.face = "bold",
                top=text_grob("Descomposición de la brecha de la pobreza",face="bold"),
                bottom=text_grob("Fuente: Calculos del autor en base a Kolenikov-Shorrocks (2005)",hjust=1,x=1))
```


# Severidad de la pobreza

La descomposición para la severidad de la pobreza:

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
#Severidad
r9<-ggplot(resultados3_2010_2013,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2010-2013")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r10<-ggplot(resultados3_2013_2016,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2013-2016")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r11<-ggplot(resultados3_2016_2019,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2016-2019")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

r12<-ggplot(resultados3_2019_2021,aes(x=Efecto,y=Proporcion))+
  geom_hline(yintercept=0)+
  geom_bar(stat="identity",color="blue",fill="royalblue")+
  scale_x_discrete(limits=c("Crecimiento","Redistribucion","Inflacion"))+
  theme_minimal()+
  labs(
    subtitle="Periodo 2019-2021")+theme(axis.title=element_text(),
                                        plot.caption.position="plot",plot.caption=element_text(hjust=0))

figura4<-ggarrange(r9,r10,r11,r12,common.legend = TRUE,"legend=bottom")
annotate_figure(figura4,fig.lab="Figura 13",fig.lab.face = "bold",
                top=text_grob("Descomposición de la severidad de la pobreza",face="bold"),
                bottom=text_grob("Fuente: Calculos del autor en base a Kolenikov-Shorrocks (2005)",hjust=1,x=1))
```


